CREATE TABLE "chapter" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "prev_chapter_id" INTEGER, "title" TEXT NOT NULL , "body" TEXT NOT NULL );
CREATE TABLE "page" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "chapter_id" INTEGER NOT NULL , "title" TEXT NOT NULL , "body" TEXT NOT NULL );
