CREATE TABLE "c_display" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "entity_id" INTEGER NOT NULL , "message" TEXT NOT NULL );
CREATE TABLE "entity" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE );
