DROP TABLE IF EXISTS "action";
DROP TABLE IF EXISTS "command";
DROP TABLE IF EXISTS "story";
DROP TABLE IF EXISTS "player";
DROP TABLE IF EXISTS "author";
DROP TABLE IF EXISTS "saved";
DROP TABLE IF EXISTS "screen";

CREATE TABLE "action" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "type" VARCHAR NOT NULL , "screen_id" INTEGER, "golem_id" INTEGER, "property" VARCHAR, "value" TEXT);
CREATE TABLE "command" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL UNIQUE, "name" VARCHAR NOT NULL UNIQUE, "targets" VARCHAR NOT NULL );
CREATE TABLE "story" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "name" VARCHAR NOT NULL  UNIQUE , "path" VARCHAR NOT NULL  UNIQUE );
CREATE TABLE "player" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "username" VARCHAR NOT NULL  UNIQUE , "password" VARCHAR NOT NULL );
CREATE TABLE "author" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "username" VARCHAR NOT NULL  UNIQUE );
CREATE TABLE "saved" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "name" VARCHAR NOT NULL , "player_id" INTEGER NOT NULL , "golem_id" INTEGER NOT NULL , "path" VARCHAR NOT NULL  UNIQUE );
CREATE TABLE "screen" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "message" TEXT NOT NULL );
